# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create config.js from secrets
        run: |
          echo "const firebaseConfig = {" > js/config.js
          echo "  apiKey: \"${{ secrets.FIREBASE_API_KEY }}\"," >> js/config.js
          echo "  authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> js/config.js
          echo "  projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> js/config.js
          echo "  storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> js/config.js
          echo "  messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> js/config.js
          echo "  appId: \"${{ secrets.FIREBASE_APP_ID }}\"" >> js/config.js
          echo "};" >> js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
